### ISSUE TITLE
Getting connected, looking for more informations on how chips works .

### ISSUE THREAD

**Issue by ayoubelmohamedi** [philiprbrenan/com.AppaApps.Silicon#9]
HI @philiprbrenan , i looked into prb.appaapps.com/zesal/pitchdeck/pitchDeck.html 
Are you active on Discords or any IRC channel ? Would be nice to get to know you ? love your projects though.

**Comment by philiprbrenan** [comment]
Hi *Ayoub*:

Thank you for your note.  Do you have the time and interest to do  either
of the following activities:

(A) Some programming on :
https://github.com/philiprbrenan/btreeBlock/blob/73cc7f8b8fe3d14684134270c6ad627f12743a34/Stuck.java#L6
(B) Start looking for venture capital to make this project a reality?

**Comment by ayoubelmohamedi** [comment]
Sure, will look into the code an see if i can help with something

**Comment by philiprbrenan** [comment]
That would be marvellous!
